### ISSUE TITLE
get_brep_part_properties doesnt exist 

### ISSUE THREAD

**Issue by Adambar24** [fusion-energy/brep_part_finder#36]
The function get_brep_part_properties doesn't exist anymore. If you would like the same print out as the readme file example it requires the function  get_part_properties_from_file.

**Comment by shimwell** [comment]
Thanks for reporting. I thought I had fixed this bug, can I check which version you are using

**Comment by shimwell** [comment]
could you run ```conda list``` and let me know the output please

**Comment by Adambar24** [comment]
brep_part_finder          0.5.2

**Comment by shimwell** [comment]
That is great, you have the latest version there.

There are a few other packages that I would be keen to konw the version number of

paramak
cad_to_dagmc
brep_to_h5m

**Comment by Adambar24** [comment]
paramak  0.8.7 
cad_to_dagmc  0.1.3
brep_to_h5m  0.4.2

Also thanks for the quick response

**Comment by shimwell** [comment]
latest versions all around. Thanks for that.

I have updated the readme now. The function name got changed to ```get_part_properties_from_file```

If you are happy this issue is resolved could you close this issue
